name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Set up SSH
      - name: Set up SSH
        run: |
          echo "${{ secrets.CI_KEY }}" > ~/.ssh_key
          chmod 600 ~/.ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # Deploy to staging server
      - name: Deploy to Staging Server
        env:
          STAGING_SERVER_IP: 18.212.54.148
        run: |
          ssh -i ~/.ssh_key ubuntu@$STAGING_SERVER_IP -o StrictHostKeyChecking=no "
            npm install -g pnpm
            # Install pnpm if not already installed
            if ! command -v pnpm &> /dev/null; then
              curl -fsSL https://get.pnpm.io/install.sh | sh -
              export PATH=\$HOME/.local/share/pnpm:\$PATH
            fi

            # Navigate to the project directory
            cd ci-next-app

            # Pull the latest changes
            git pull origin main

            # Install dependencies
            pnpm install

            # Build the project
            pnpm run build

            # Restart PM2 processes
            pm2 restart fe
            pm2 restart http
            pm2 restart ws
          "