name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Set up SSH
      - name: Set up SSH
        run: |
          echo "${{ secrets.CI_KEY }}" > ~/.ssh_key
          chmod 600 ~/.ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" > /home/runner/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts 
          ssh -i ~/.ssh_key ubuntu@18.212.54.148  -t "cd ci-next-app && git pull origin main && export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && sudo npm install -g pnpm && pnpm install && pnpm run build && pm2 restart fe && pm2 restart http && pm2 restart ws"