name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Set up SSH
      - name: Set up SSH
        run: |
          echo "${{ secrets.CI_KEY }}" > ~/.ssh_key
          if [ ! -d ~/.ssh ]; then
            mkdir -p ~/.ssh
          fi
          touch /home/runner/.ssh/known_hosts
          chmod 600 ~/.ssh_key
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      # Deploy to staging server
      - name: Deploy to Staging Server
        env:
          STAGING_SERVER_IP: 18.212.54.148
        run: |
          ssh -i ~/.ssh_key ubuntu@$STAGING_SERVER_IP -o StrictHostKeyChecking=no "
            curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm &&
            cd ci-next-app &&
            git pull origin main &&
            pnpm install &&
            pnpm run build &&
            pm2 restart fe &&
            pm2 restart http &&
            pm2 restart ws
          "
